name: vxg_playersdk
description: Flutter plugin to use the VXG Player SDK, which enables playback of media files and streams for your apps.
homepage: https://www.videoexpertsgroup.com/
repository: https://github.com/VideoExpertsGroup/VXG.Media.SDK.Flutter/tree/master/packages/mediasdk/playersdk/playersdk
version: 0.0.2

false_secrets:
  - example/**

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: vxg.playersdk
        pluginClass: PlayerSDKPlugin
      ios:
        pluginClass: PlayerSDKPlugin
